import type { CategoryConfig } from "./types.ts";

/** Celulares — metodologia v1.0 (docs/15 §15.3). */
export const celulares: CategoryConfig = {
  vertical: "tecnologia",
  slug: "celulares",
  name: "Celulares",
  nameSingular: "Celular",
  synonyms: ["celular", "celulares", "smartphone", "smartphones", "telefone", "aparelho"],
  variantAxes: ["storage", "color"],
  priceBands: [1000, 1500, 2000, 3000, 5000],
  groups: [
    { key: "display", label: "Tela" },
    { key: "performance", label: "Desempenho" },
    { key: "camera", label: "Câmera" },
    { key: "battery", label: "Bateria" },
    { key: "software", label: "Software" },
    { key: "connectivity", label: "Conectividade" },
    { key: "build", label: "Construção" },
  ],
  attributes: [
    { key: "screen_inches", label: "Tamanho da tela", group: "display", type: "decimal", unit: "pol", filterable: true, plausible: { min: 3, max: 9 } },
    { key: "screen_type", label: "Tipo de tela", group: "display", type: "enum", enumValues: [{ key: "oled", label: "OLED" }, { key: "lcd", label: "LCD" }], filterable: true },
    { key: "screen_is_oled", label: "Tela OLED", group: "display", type: "bool", higherIsBetter: true, comparable: false },
    { key: "screen_resolution", label: "Resolução", group: "display", type: "text" },
    { key: "refresh_rate_hz", label: "Taxa de atualização", group: "display", type: "int", unit: "Hz", higherIsBetter: true, filterable: true, plausible: { min: 30, max: 240 } },
    { key: "peak_brightness_nits", label: "Brilho máximo", group: "display", type: "int", unit: "nits", higherIsBetter: true, plausible: { min: 200, max: 6000 } },
    { key: "chipset", label: "Processador", group: "performance", type: "text" },
    { key: "cpu_benchmark", label: "Benchmark de CPU (multi-core)", group: "performance", type: "int", higherIsBetter: true, plausible: { min: 100, max: 20000 } },
    { key: "gpu_benchmark", label: "Benchmark de GPU", group: "performance", type: "int", higherIsBetter: true, plausible: { min: 100, max: 50000 } },
    { key: "ram_gb", label: "RAM", group: "performance", type: "int", unit: "GB", higherIsBetter: true, filterable: true, plausible: { min: 1, max: 32 } },
    { key: "storage_gb", label: "Armazenamento", group: "performance", type: "int", unit: "GB", higherIsBetter: true, filterable: true, plausible: { min: 16, max: 2048 } },
    { key: "main_camera_mp", label: "Câmera principal", group: "camera", type: "int", unit: "MP", higherIsBetter: true, plausible: { min: 2, max: 300 } },
    { key: "optical_zoom_x", label: "Zoom óptico", group: "camera", type: "decimal", unit: "x", higherIsBetter: true, plausible: { min: 1, max: 15 } },
    { key: "ois", label: "Estabilização óptica", group: "camera", type: "bool", higherIsBetter: true },
    { key: "camera_test_score", label: "Nota do teste de câmera (cenas padronizadas)", group: "camera", type: "decimal", higherIsBetter: true, plausible: { min: 0, max: 10 } },
    { key: "front_camera_mp", label: "Câmera frontal", group: "camera", type: "int", unit: "MP", higherIsBetter: true, plausible: { min: 1, max: 100 } },
    { key: "battery_mah", label: "Bateria", group: "battery", type: "int", unit: "mAh", higherIsBetter: true, filterable: true, plausible: { min: 1000, max: 10000 } },
    { key: "battery_test_hours", label: "Autonomia no teste de streaming", group: "battery", type: "decimal", unit: "h", higherIsBetter: true, plausible: { min: 3, max: 40 } },
    { key: "charging_w", label: "Carregamento", group: "battery", type: "int", unit: "W", higherIsBetter: true, plausible: { min: 5, max: 240 } },
    { key: "os", label: "Sistema", group: "software", type: "enum", enumValues: [{ key: "android", label: "Android" }, { key: "ios", label: "iOS" }], filterable: true },
    { key: "os_update_years", label: "Anos de atualização de sistema", group: "software", type: "int", unit: "anos", higherIsBetter: true, plausible: { min: 0, max: 10 } },
    { key: "security_update_years", label: "Anos de atualização de segurança", group: "software", type: "int", unit: "anos", higherIsBetter: true, plausible: { min: 0, max: 10 } },
    { key: "five_g", label: "5G", group: "connectivity", type: "bool", filterable: true },
    { key: "nfc", label: "NFC", group: "connectivity", type: "bool", filterable: true },
    { key: "wifi", label: "Wi-Fi", group: "connectivity", type: "text" },
    { key: "bluetooth", label: "Bluetooth", group: "connectivity", type: "text" },
    { key: "ip_rating", label: "Resistência à água", group: "build", type: "enum", enumValues: [{ key: "none", label: "Sem certificação" }, { key: "ip54", label: "IP54" }, { key: "ip67", label: "IP67" }, { key: "ip68", label: "IP68" }] },
    { key: "water_resistance_level", label: "Nível de resistência (0–3)", group: "build", type: "int", higherIsBetter: true, plausible: { min: 0, max: 3 } },
    { key: "weight_g", label: "Peso", group: "build", type: "int", unit: "g", higherIsBetter: false, plausible: { min: 80, max: 350 } },
    { key: "dimensions_mm", label: "Dimensões", group: "build", type: "text" },
    { key: "premium_materials", label: "Materiais premium (vidro/metal)", group: "build", type: "bool", higherIsBetter: true },
    { key: "warranty_months", label: "Garantia", group: "build", type: "int", unit: "meses", plausible: { min: 0, max: 60 } },
  ],
  methodology: {
    category: "celulares",
    version: "v1.0",
    editorialAdjustMax: 0.5,
    criteria: [
      { key: "performance", label: "Desempenho", weight: 0.2, inputs: [
        { attr: "cpu_benchmark", weight: 0.5, direction: "higher" },
        { attr: "gpu_benchmark", weight: 0.3, direction: "higher" },
        { attr: "ram_gb", weight: 0.2, direction: "higher" },
      ] },
      { key: "camera", label: "Câmera", weight: 0.2, inputs: [
        { attr: "camera_test_score", weight: 0.6, direction: "higher" },
        { attr: "optical_zoom_x", weight: 0.2, direction: "higher" },
        { attr: "ois", weight: 0.1, direction: "higher" },
        { attr: "main_camera_mp", weight: 0.1, direction: "higher", log: true },
      ] },
      { key: "battery", label: "Bateria", weight: 0.15, inputs: [
        { attr: "battery_test_hours", weight: 0.6, direction: "higher" },
        { attr: "battery_mah", weight: 0.25, direction: "higher" },
        { attr: "charging_w", weight: 0.15, direction: "higher" },
      ] },
      { key: "display", label: "Tela", weight: 0.15, inputs: [
        { attr: "peak_brightness_nits", weight: 0.5, direction: "higher" },
        { attr: "refresh_rate_hz", weight: 0.3, direction: "higher" },
        { attr: "screen_is_oled", weight: 0.2, direction: "higher" },
      ] },
      { key: "software", label: "Software e atualizações", weight: 0.1, inputs: [
        { attr: "os_update_years", weight: 0.6, direction: "higher" },
        { attr: "security_update_years", weight: 0.4, direction: "higher" },
      ] },
      { key: "build", label: "Construção", weight: 0.1, inputs: [
        { attr: "water_resistance_level", weight: 0.5, direction: "higher" },
        { attr: "premium_materials", weight: 0.3, direction: "higher" },
        { attr: "weight_g", weight: 0.2, direction: "lower" },
      ] },
      { key: "value", label: "Custo-benefício", weight: 0.1, inputs: [], computed: "value_for_money" },
    ],
  },
  profiles: [
    { key: "fotografia", label: "Fotos e vídeos", description: "Câmera é prioridade", priorities: { camera: "high", display: "medium", battery: "medium" } },
    { key: "jogos", label: "Jogos", description: "Desempenho e tela fluida", priorities: { performance: "high", display: "high", battery: "medium" } },
    { key: "trabalho", label: "Trabalho e produtividade", description: "Bateria, atualizações e desempenho", priorities: { battery: "high", software: "high", performance: "medium" } },
    { key: "basico", label: "Uso básico", description: "Redes sociais, mensagens e custo baixo", priorities: { value: "high", battery: "medium" } },
    { key: "bateria", label: "Bateria que dura", description: "Passar o dia longe da tomada", priorities: { battery: "high", value: "medium" } },
  ],
  advisorQuestions: [
    { key: "use", question: "Para que você mais vai usar o celular?", multi: true, options: [
      { key: "fotografia", label: "Fotos e vídeos", apply: { priorities: { camera: "high" } } },
      { key: "jogos", label: "Jogos", apply: { priorities: { performance: "high", display: "high" } } },
      { key: "trabalho", label: "Trabalho", apply: { priorities: { battery: "high", software: "high" } } },
      { key: "basico", label: "Redes sociais e mensagens", apply: { priorities: { value: "high" } } },
    ] },
    { key: "budget", question: "Até quanto você quer gastar?", options: [
      { key: "1500", label: "Até R$ 1.500", apply: { budgetMax: 1500 } },
      { key: "2500", label: "Até R$ 2.500", apply: { budgetMax: 2500 } },
      { key: "4000", label: "Até R$ 4.000", apply: { budgetMax: 4000 } },
      { key: "any", label: "Sem limite definido", apply: { budgetMax: null } },
    ] },
    { key: "os", question: "Tem preferência de sistema?", options: [
      { key: "android", label: "Android", apply: { exclude: { os: ["ios"] } } },
      { key: "ios", label: "iPhone (iOS)", apply: { exclude: { os: ["android"] } } },
      { key: "any", label: "Tanto faz", apply: {} },
    ] },
    { key: "size", question: "Prefere um celular menor?", options: [
      { key: "compact", label: "Sim, até 6,3\"", apply: { ranges: { screen_inches: { max: 6.3 } } } },
      { key: "any", label: "Tanto faz", apply: {} },
    ] },
  ],
  compareAttrs: [
    "chipset", "ram_gb", "storage_gb", "screen_inches", "screen_type", "refresh_rate_hz", "peak_brightness_nits",
    "main_camera_mp", "optical_zoom_x", "ois", "front_camera_mp", "battery_mah", "battery_test_hours", "charging_w",
    "os", "os_update_years", "five_g", "nfc", "ip_rating", "weight_g", "warranty_months",
  ],
  highlightAttrs: ["chipset", "ram_gb", "storage_gb", "screen_inches", "battery_mah", "main_camera_mp"],
};

